#import "./fragments/Company.gql"

query allCompanies {
	allCompanies {
		...Company
		geoLocation {
			id
			latitude
			longitude
		}
		offers {
			id
		}
		tags {
			id
		}
		users {
			id
		}
	}
}
